#!/usr/bin/env python3
import sys

for line in sys.stdin:
    words = line.strip().split()
    uttid = words[-1]
    transcript = ' '
    for word in words[0:-1]:
        word = word.lower()
        if word in  ('[inaudible]', '[laughs]', '[noise]'):
            continue
        if word in  ('mhm', 'mm', 'mmm'):
            word = 'hmm'
        transcript = transcript + ' ' + word
    print("{} {}".format(uttid, transcript))
